### ISSUE TITLE
HDB++ servers

### ISSUE THREAD

**Issue by piogor** [3Controls/tangobox#17] opened 2017-09-13 12:19 UTC
The HDB++ servers should be installed on the container/image`tangobox-archivning` (see, #15)

**Comment by andygotz** [comment] 2017-09-13 15:02
Contact Stuart James (github user = chedburgh) for installing HDB++. He has created debian packages and docker containers for HDB++.

**Comment by chedburgh** [comment] 2017-09-14 06:03
I am just testing debian packages for libhdbpp and libhdbpp-cassandra. I was planning to upload them to bintray when finished, so I will let you know.

I can also help out making changes to the Dockerfile to install them if needed.

**Comment by stanislaw47** [comment] 2017-09-20 07:29
Hello @chedburgh, 
have you finished testing those packages?

**Comment by chedburgh** [comment] 2017-09-20 11:36
Not yet, sorry. I am hoping to put the debian packages on bintray in then day or so. I will update the ticket then with progress to keep you informed.

If I have time I am going to try build a meta package to install most of the HDBPP items.

**Comment by stanislaw47** [comment] 2017-09-20 13:30
That's great! I'm looking forward to hear from you.

**Comment by stanislaw47** [comment] 2017-09-28 08:05
Hi @chedburgh, how's packages stuff going?

**Comment by chedburgh** [comment] 2017-09-28 08:41
I had a few delays, but I am going to try get some packages to you today (perhaps tomorrow morning). I can either attach them here directly or try organise a repository to grab them from.

The packages are dependent on the libtango9 debian package (and other libraries), I am not sure how you have your install set up, but you may have to force the install to ignore dependencies due to this. If you have tango controls working, then it will mean you have all the dependencies required for HDB++.

You are using MySQL correct? Not Cassandra.

**Comment by stanislaw47** [comment] 2017-09-28 08:45
Thank you for the answer. Yes, we are using MySQL, that's correct.

**Comment by chedburgh** [comment] 2017-09-28 08:59
Ok, I will package libhdbpp-mysql also.

**Comment by chedburgh** [comment] 2017-09-28 11:30
Can I just check what you need. I am assuming the following:

- hdbpp-cm
- hdbpp-es
- libhdbpp
- libhdbpp-mysql

**Comment by stanislaw47** [comment] 2017-09-28 11:57
Yes, exactly. Those device servers will be running on docker container

**Comment by chedburgh** [comment] 2017-09-28 14:42
@stanislaw47 I have 4 deb files I can attach to this ticket. You are welcome to try install them locally by installing them with "dpkg -i package.deb". You can ignore their dependencies ("dpkg --force -i package.deb").  If you want apt to install the dependencies, run "apt-get install -f" after "dpkg -i package.deb".

I have only just finished these, and not tested them or documented them in anyway. So I can not guarantee anything will work :) They are not yet even on the master branch of their respective github repos.

Further, I am bulding on debian9 (stretch), which is a change over point for mysql packages. I have linked against whats available in debian9, and these packages are only availabe in debian8 via jessie-backports. This gives is a linkage dependency on libmariadbclient.so.18. Are you using MarieDB?

If you run dpkg -c package.deb you can see whats inside and where it will be installed. Basically, libs in /usr/lib and binaries in /usr/bin, other stuff /usr/share.

I am going to add the packages to bintray tomorrow, and will be able to offer a repository to pull from then, but in the meantime you may want to test with these and make progress (if possible). If you do try, please drop me feedback here and I will try help out.

[packages.zip](https://github.com/3Controls/tangobox/files/1341279/packages.zip)

**Comment by chedburgh** [comment] 2017-10-02 12:34
@stanislaw47 The test packages are now in a bintray repo: https://bintray.com/tango-controls/debian

They have been built and tested on debian stretch, so instructions are debian. These are pre-offical packages, the pull requests for the debian package work has not been integrated yet. The packages will be regenerated as offical v1 releases when this happens.

Add bintray to your repo:
echo "deb https://dl.bintray.com/tango-controls/debian stretch main" | sudo tee -a /etc/apt/sources.list

Update apt:
apt-get update

Then install:
apt-get install hdb++mysql

hdb++mysql is a metapackage that will pull everything it needs to run, including libtango9 and all its deps. I have not tested this on other platforms, i.e. ubuntu etc. 

As mentioned before, you could ignore deps if required. I'd be interested to hear how these work for you. If you have trouble youy may need to build the binaries yourself. This is straight forward. I have updated every hdb++ repo with a new buid instrustions and enhanced makefiles (or cmake file). See branch "Build and Package". If you need help just drop a message on here.

Thanks
Stuart

**Comment by piogor** [comment] 2017-10-02 12:52
Since the packages are taking dependencies which may conflict with our base image I suggest to create a separate “hdbpp” image and then run a separate container tangobox-hdbpp.

**Comment by chedburgh** [comment] 2017-10-02 13:10
Good suggestion. I have had it all installing fine on basic debian stretch docker container, so thats one good candidate to try.

**Comment by stanislaw47** [comment] 2017-10-04 10:26
Thank you @chedburgh for your commitment. After following your instructions, I've encountered following problem: 
```
W: The repository 'deb https://dl.bintray.com/tango-controls/debian stretch Realese' is not signed.
The following packages have unmet dependencies:
hdb++mysql : Depends: hdb++es but it is not installable
                        Depends: hdb++cm but it is not going to be installed
                        Depends: libhdb++mysql6 but it is not going to be installed
E: Unable to correct problems, you have held broken packages
```
After trying to install those packages manually, I get this:
```
E: Package 'hdb++es' has no installation candidate
```
base docker image: Ubuntu 16.04 

I'd *really* like to avoid building packages froum source and thus, my question is: are this errors severe and caused by Ubuntu?

**Comment by chedburgh** [comment] 2017-10-04 10:50
@stanislaw47 Actually its great to have someone trying the packages.

Ok, I tested this in a docker container. This is what you should be seeing:

```
root@437eaa462d0c:/# apt-get install libhdb++mysql6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  default-mysql-client libaio1 libcos4-1 libdbd-mysql-perl libdbi-perl libhdb++6 libjemalloc1
  liblog4tango5v5 libmariadbclient18 libncurses5 libomniorb4-1 libomnithread3c2 libpgm-5.2-0
  libreadline5 libsodium18 libtango9 libterm-readkey-perl libzmq5 mariadb-client-10.1
  mariadb-client-core-10.1 mariadb-common mysql-common readline-common tango-common
Suggested packages:
  libclone-perl libmldbm-perl libnet-daemon-perl libsql-statement-perl readline-doc
The following NEW packages will be installed:
  default-mysql-client libaio1 libcos4-1 libdbd-mysql-perl libdbi-perl libhdb++6
  libhdb++mysql6 libjemalloc1 liblog4tango5v5 libmariadbclient18 libncurses5 libomniorb4-1
  libomnithread3c2 libpgm-5.2-0 libreadline5 libsodium18 libtango9 libterm-readkey-perl
  libzmq5 mariadb-client-10.1 mariadb-client-core-10.1 mariadb-common mysql-common
  readline-common tango-common
0 upgraded, 25 newly installed, 0 to remove and 2 not upgraded.
Need to get 17.5 MB of archives.
After this operation, 103 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
```

My docker image is based on debian:stretch. What is your image based on?

I have added the following to my /etc/apt/sources.list 

`deb [trusted=yes] https://dl.bintray.com/tango-controls/debian stretch main`

The [trusted=yes] should not make a difference (it does not here when I test it), but it will get rid of the complaints about the repo not being signed.

Your repository line looks like it includes "Realese" instead of "main". Could this be the problem?

Finally, what is the architecture? amd64? The packages were build for amd64 and uploaded with this keyword. Could be this is having an effect.

Thanks
Stuart

**Comment by stanislaw47** [comment] 2017-10-04 11:22
Thanks for quick answer!
I'm using `base` docker image. Actually it's just `ubuntu:16.04` with Tango and PyTango. I suppose it's problem with `release` instead of `main` because this is what I get after adding repo:

![image](https://user-images.githubusercontent.com/27857846/31173201-ecc91ae6-a906-11e7-8d9a-0c793877b4b5.png)

**Comment by chedburgh** [comment] 2017-10-04 11:33
You are correct, I think there is a package problem.  Shall comment again shortly after some testing (I need to find what changed over the last day or two!).

**Comment by stanislaw47** [comment] 2017-10-04 11:35
Great, I'll just wait for any info.

**Comment by chedburgh** [comment] 2017-10-04 11:46
Can you just test libhdb++mysql6

I can not see what the problem is with the other packages, seems to related to some I reuploaded yesterday. I am going to remove the current version and reupload it, I will let you know when they are ready. Should not take long.

**Comment by stanislaw47** [comment] 2017-10-04 12:05
I've tried `libhdb++mysql6` and it yields about dependencies (`libtango9`, `default-mysql-client` and `libmariadbclient18`) which are 'not installable'. Not mentioning I already have them installed.

**Comment by chedburgh** [comment] 2017-10-04 12:38
I can not tell what the problem was, so I reuploaded the packages and they work now. Please try again and let me know what happens.

Regarding the dependencies above, I am not sure. The packages were build and tested on debian stretch. One idea is to ignore dependencies on the hdb++ packages, and then install them manually yourself.

**Comment by chedburgh** [comment] 2017-10-04 13:35
I have just tried on debian jessie, and there are stdc++ version differences. I suspect you will hit the same difference. Suggest either a manual build for each, or use a debian stretch container.

**Comment by stanislaw47** [comment] 2017-10-04 13:41
I've noticed that. Well, I really appreciate your help but I'll try building from source.

**Comment by chedburgh** [comment] 2017-10-04 13:49
All the components you need have improved build systems, but on a branch as the pull requests have not yet been reviewed. 

If you look on branch "Build-And-Package", the Makefiles have been improved, some replaced with cmake, and there is far more documentation to get the components built.

Any problems just pop and message on here and I will help out. I am about to test build some on  centos, so I will be doing some similar steps!

**Comment by stanislaw47** [comment] 2017-10-04 13:55
Thank you, in case of any issues I'll let you know.

**Comment by stanislaw47** [comment] 2017-10-04 14:13
Ok, first issue:
On `base` docker image, Tango has been installed in `/usr/local` as opposed to `/usr/local/tango`. During installation I receive 'not found' sort of errors, which indicates that there's a paths issue going on. Is there any way to adjust Tango home path?

**Comment by chedburgh** [comment] 2017-10-04 14:24
I am not sure what you are installing. This is documented on each repositories README.md or (for more complex builds) INSTALL.md (remember to check the branch I mentioned above).

Cmake based builds have the flag CMAKE_INCLUDE_PATH.

Makefile based builds have a series of enviroment variables: 

TANGO_INC	Tango include files directory
TANGO_LIB	Tango lib files directory
OMNIORB_LIB	Omniorb lib files directory
LIBHDBPP_INC	Libhdb++ include files directory
LIBHDBPP_LIB	Libhdb++ lib files directory

**Comment by chedburgh** [comment] 2017-10-04 14:27
Example

`export TANGO_INC=/usr/local/include/tango`

If thats where the headers are.

**Comment by stanislaw47** [comment] 2017-10-04 15:08
Actually, plans have changed and now I'm working on debian-based image. Hope it'll be easier

**Comment by chedburgh** [comment] 2017-10-04 16:58
If you use debian stretch, you can base on the stretch slim image (cut down
version). A simple pull of hdb++mysql will get you everything you need to
run.

I am interested to see how you set up the ports. I had to bind to the host
network to get the ports open to reach other pcs. We can not set the zmq
ports.

**Comment by stanislaw47** [comment] 2017-10-05 08:08
I've tried installing only `hdb++mysql` and it indeed pulls everything what I need, but it seems that Tango packages are broken somehow. It says that it has been installed but when try searching it, there's nothing. Can you confirm that packages are broken? Maybe I'm just doing it wrong but manually installing Tango packages with dependencies changes nothing.

**Comment by chedburgh** [comment] 2017-10-05 08:10
What are you trying to install on? I will test hdb++mysql on debian stretch in the meantime.

**Comment by stanislaw47** [comment] 2017-10-05 08:12
I'm trying to install `hdb++mysql` on fresh `debian:stretch-slim` base image. It says it installs also Tango, omniORB, ZMQ and other, hdb++ dependencies but when I log into container and search for Tango files, there's nothing.

**Comment by chedburgh** [comment] 2017-10-05 08:25
OK, let me check into it and see what I can find.

**Comment by chedburgh** [comment] 2017-10-05 09:09
This appears ok for me, lets see if we can find whats causing the problem. 

So, here are my exact steps:

`docker run -it debian:stretch-slim bash`

I setup my proxy next. Then:

```
apt-get update
apt-get -y install apt-transport-https
echo "deb [trusted=yes] https://dl.bintray.com/tango-controls/debian stretch main" | tee -a /etc/apt/sources.list
apt-get update
```

Order is important above. Add the bintray repo before the package and you will break apt-get.

`apt-get install hdb++mysql`

On debian:stretch I am offered:

```
The following additional packages will be installed:
  default-mysql-client hdb++cm hdb++es libaio1 libcos4-1 libdbd-mysql-perl libdbi-perl
  libgdbm3 libgpm2 libhdb++6 libhdb++mysql6 libjemalloc1 liblog4tango5v5 libmariadbclient18
  libncurses5 libomniorb4-1 libomnithread3c2 libperl5.24 libpgm-5.2-0 libreadline5 libsodium18
  libssl1.0.2 libtango9 libterm-readkey-perl libzmq5 mariadb-client-10.1
  mariadb-client-core-10.1 mariadb-common mysql-common perl perl-base perl-modules-5.24
  readline-common rename tango-common
Suggested packages:
  libclone-perl libmldbm-perl libnet-daemon-perl libsql-statement-perl gpm perl-doc
  libterm-readline-gnu-perl | libterm-readline-perl-perl make readline-doc
The following NEW packages will be installed:
  default-mysql-client hdb++cm hdb++es hdb++mysql libaio1 libcos4-1 libdbd-mysql-perl
  libdbi-perl libgdbm3 libgpm2 libhdb++6 libhdb++mysql6 libjemalloc1 liblog4tango5v5
  libmariadbclient18 libncurses5 libomniorb4-1 libomnithread3c2 libperl5.24 libpgm-5.2-0
  libreadline5 libsodium18 libssl1.0.2 libtango9 libterm-readkey-perl libzmq5
  mariadb-client-10.1 mariadb-client-core-10.1 mariadb-common mysql-common perl
  perl-modules-5.24 readline-common rename tango-common
The following packages will be upgraded:
  perl-base
1 upgraded, 35 newly installed, 0 to remove and 0 not upgraded.
Need to get 26.9 MB of archives.
After this operation, 148 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
```

On debian-stretch-slim I am offered:

```
The following additional packages will be installed:
  default-mysql-client hdb++cm hdb++es libaio1 libcos4-1 libdbd-mysql-perl libdbi-perl
  libgdbm3 libgpm2 libhdb++6 libhdb++mysql6 libjemalloc1 liblog4tango5v5 libmariadbclient18
  libncurses5 libomniorb4-1 libomnithread3c2 libperl5.24 libpgm-5.2-0 libreadline5 libsodium18
  libssl1.0.2 libtango9 libterm-readkey-perl libzmq5 mariadb-client-10.1
  mariadb-client-core-10.1 mariadb-common mysql-common netbase perl perl-base
  perl-modules-5.24 readline-common rename tango-common
Suggested packages:
  libclone-perl libmldbm-perl libnet-daemon-perl libsql-statement-perl gpm perl-doc
  libterm-readline-gnu-perl | libterm-readline-perl-perl make readline-doc
The following NEW packages will be installed:
  default-mysql-client hdb++cm hdb++es hdb++mysql libaio1 libcos4-1 libdbd-mysql-perl
  libdbi-perl libgdbm3 libgpm2 libhdb++6 libhdb++mysql6 libjemalloc1 liblog4tango5v5
  libmariadbclient18 libncurses5 libomniorb4-1 libomnithread3c2 libperl5.24 libpgm-5.2-0
  libreadline5 libsodium18 libssl1.0.2 libtango9 libterm-readkey-perl libzmq5
  mariadb-client-10.1 mariadb-client-core-10.1 mariadb-common mysql-common netbase perl
  perl-modules-5.24 readline-common rename tango-common
The following packages will be upgraded:
  perl-base
1 upgraded, 36 newly installed, 0 to remove and 0 not upgraded.
Need to get 26.9 MB of archives.
After this operation, 148 MB of additional disk space will be used.
```

Check install:

`
root@c5553c805ed0:/# ls -l /usr/lib/x86_64-linux-gnu/libtango.so*  
lrwxrwxrwx 1 root root      17 Jan 16  2017 /usr/lib/x86_64-linux-gnu/libtango.so.9 -> libtango.so.9.2.5
-rw-r--r-- 1 root root 6713216 Jan 16  2017 /usr/lib/x86_64-linux-gnu/libtango.so.9.2.5
`

I can query the package:

```
root@8ec6799c52e9:/# dpkg -L libtango9
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libtango.so.9.2.5
/usr/share
/usr/share/doc
/usr/share/doc/libtango9
/usr/share/doc/libtango9/changelog.Debian.gz
/usr/share/doc/libtango9/copyright
/usr/lib/x86_64-linux-gnu/libtango.so.9
root@8ec6799c52e9:/# apt-cache show libtango9
Package: libtango9
Source: tango
Version: 9.2.5a+dfsg1-2
Installed-Size: 6575
Maintainer: Debian Science Maintainers <debian-science-maintainers@lists.alioth.debian.org>
Architecture: amd64
Depends: libc6 (>= 2.14), libcos4-1 (>= 4.1.6), libgcc1 (>= 1:3.0), liblog4tango5v5, libomniorb4-1 (>= 4.1.6), libomnithread3c2 (>= 4.0.6), libstdc++6 (>= 6), libzmq5 (>= 3.2.3+dfsg), tango-common
Description: TANGO distributed control system - shared library
Description-md5: 07b63e916b41f8d54e9fbf0df09a98a0
Multi-Arch: same
Homepage: http://www.tango-controls.org
Tag: role::shared-lib
Section: libs
Priority: extra
Filename: pool/main/t/tango/libtango9_9.2.5a+dfsg1-2_amd64.deb
Size: 1601796
MD5sum: c69d8055d77eb76b28870a48a2f8dbe0
SHA256: 21313702940cc89fafbcb29a10ed5d8f42e308abda9bddc3dc79a4877c2101cc
```

Finally, I am just running a simple container here, its not persistent. Soon as I log out and back in, all the above is lost. I am not mounting any volmes to persist the state. I am assuming you are putting all this into a Dockerfile then running that image? If so, what kind of RUN command are you using to run the install?

Something like 

```
RUN apt-get update && \
    apt-get -y install apt-transport-https && \
    echo "deb [trusted=yes] https://dl.bintray.com/tango-controls/debian stretch main" | \
        tee -a /etc/apt/sources.list && \
    apt-get update
    apt-get autoremove -y && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN  apt-get update && \
    apt-get -y install  hdb++mysql && \
    apt-get autoremove -y && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

Would probably work (I have not tested this on a docker build, could be a syntax error in there.).

Thanks
Stuart

(EDIT: There was an error in that docker file command!)

**Comment by stanislaw47** [comment] 2017-10-05 10:17
Well, thanks to you I realised that packages are just placed in different directories. I just couldn't find them!

**Comment by chedburgh** [comment] 2017-10-05 10:27
Excelent.

Are you installing tango from the source package or via debian package? It should be the same if package. Where did you find them?

The tango source package, once built and installed, does differ from the debian package. Causes a few problems with headers etc.

**Comment by stanislaw47** [comment] 2017-10-05 11:13
I install Tango via debian packages and I hope it should allow me avoid any problems. 

Well, main difference was that files were not in `/usr/local/somewhere` but directly in `/usr/somewhere`

**Comment by chedburgh** [comment] 2017-10-05 11:18
That makes sense. 

For debian, /usr/etc is used to package install via root. /usr/local/etc is used for manual installs via make install etc.

Sounds like this is on its way now. Let me know if you have any more problems.

**Comment by stanislaw47** [comment] 2017-10-05 14:22
Ok, I believe that packages are installed correctly. I've managed to start CM and ES DServers but there are some problems. To made myself clear, I've just started those Dservers without any configuration. I wasn't able to find full, coherent configuration guide for those DServers. Do you know any?

**Comment by chedburgh** [comment] 2017-10-05 14:40
I am not aware of anything off the top of my head. I am hoping to add something about installation and setup on the readthedocs site when I get time (with luck tomorrow)

I am only familir with the cassandra configuration. 

At a guess, add the device servers to the database like any other, then start them.

Using jive, you add the config to its properties (LibConfiguration property). There is some details about LibConfiguration here: 

[here](http://tango-controls.readthedocs.io/en/latest/administration/services/hdbpp/hdb++-design-guidelines.html#class-properties)

If I find anything else I will add it.

**Comment by stanislaw47** [comment] 2017-10-05 14:41
Thanks, I'll try that

**Comment by stanislaw47** [comment] 2017-10-06 11:44
Hi, it's me again.
After some struggling with databases, I put it up and tried running DServers. They don't even start (blue dot in Astor), they just remain in fault state (red dot). I've checked Standard Error field in Astor: nothing. DServer logs: empty. After running them by hand, I get this:
```
HdbClient: Configuration parsing error looking for key 'libanme='
```

I guess it's configuration error but I have no idea what and where shall I change. Properties in Astor? 
@andygotz @chedburgh, any thoughts on what's wrong?

**Comment by chedburgh** [comment] 2017-10-06 11:49
You need to set libname=libhdb++mysql.6 for the mysql backend.

**Comment by chedburgh** [comment] 2017-10-06 11:52
You can set this in the properties in Jive.

See the documentation about the configuration: http://tango-controls.readthedocs.io/en/latest/administration/services/hdbpp/hdb++-design-guidelines.html#class-properties

**Comment by stanislaw47** [comment] 2017-10-06 11:56
Hello @chedburgh 
Do you mean to add line
```
libname=libhdb++mysql.6
```
to the LibConfiguration property?

**Comment by chedburgh** [comment] 2017-10-06 12:00
Yes.

**Comment by chedburgh** [comment] 2017-10-06 12:01
Documentation looks like it is out of date, as it does not add that.

**Comment by stanislaw47** [comment] 2017-10-06 12:53
Ok, another question: `libhdb++mysql.6` doesn't work, I've checked out my MySQL and actually it's MariaDB, version 10.1.26. Shall I convert to pure MySQL or there is `libname` for MariaDB?

**Comment by chedburgh** [comment] 2017-10-06 13:13
Sorry, its libhdb++mysql.so.6 (My bad, I missed the .so!!!).

You are telling it what hdb++ backend library to load a shared library. libhdb++mysql.so.6 is installed when you install the debian packages (via hdb++mysql). The library itself is linked again MariaDB.

**Comment by stanislaw47** [comment] 2017-10-06 13:49
After adding networking options and proper users, I can announce that it works :)

**Closed as completed by stanislaw47** 2017-10-06 13:49 UTC
